### ISSUE TITLE
Major version warning

### ISSUE THREAD

**Issue by cophilot** [cophilot/templify#6]
Give a warning when wanting to upgrade to a new major version

**Comment by RounakJoshi09** [comment]
Hi @cophilot , Loved your work on templify.  Your tool is a game-changer for the community, as it saves us from the tedious task of creating files in the same format over and over again. It's been a huge help in many situations. In your journey of making developers life easier, I want to come along and contribute to take this tool to what you have dreamt of. 

In an attempt of that I have tried to solve this issue, and I have mostly done with writing code, I just have doubts in the warning message which we want to show as a part of warning. In my view , we should use two separate warning messages for these cases

1. When user has explicity mentioned the major version update (through flag)
ex:- 
![image](https://github.com/user-attachments/assets/96e9c9d7-76f9-4220-bb9a-0456a6b7e550)

2. When user are updating to the latest stable version, which might have major version change, something like this
![image](https://github.com/user-attachments/assets/d8350dd5-933e-4e02-94b7-b67d1b28eed1)

Please confirm , if you are okay with these messages or want some changes in them.

Thankyou,

**Comment by cophilot** [comment]
Hey @RounakJoshi09 , thank you very much for your warm words, I am happy to hear that _templify_ makes your life easier :)

I think both the idea of two warning messages and the messages itself are great and should definitely be added. Only one suggestion: Maybe add the link to the CHANGELOG (https://github.com/cophilot/templify/blob/master/CHANGELOG.md) to the message, to make it easier for the user to look up the changes.

Thank you and I am looking forward to your PR!
